fix: Update package and ts config to enable installing directly from fork
locally I'd like to change my package.json to `"eth-testing": "HereNotThere/eth-testing#personal-sign-install-npm-skip",` so that I can make edits to this repo and test it locally.

For that to work we need to change two things:

Add `install` step to package.json - otherwise, no 'lib' folder is built and vscode doesn't see any types

add `skipLibCheck:true` to tsconfig.json. Not sure why this isn't default, our node_modules folder has copies of jest and mocha, and running the install script will fail with this error otherwise:

```
node_modules/@types/mocha/index.d.ts:2680:13 - error TS2403: Subsequent
variable declarations must have the same type.  Variable 'beforeEach'
must be of type 'Lifecycle',  but here has type 'HookFunction'.
```